name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment (dev, sit, uat, prd)"
        required: true
        type: choice
        options:
          - dev
          - sit
          - uat
          - prd
      REGION:
        description: "AWS Region"
        required: true
        type: choice
        options:
          - eu-west-1
          - eu-west-2
          - ap-southeast-2

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
